# Allow long paragraphs (NO hard wrap)
MD013: false

# Allow multiple blank lines if desired
MD012:
  maximum: 2

# Doxygen-friendly:
# Requires blank line between paragraphs (good)
MD009: false # trailing spaces (Doxygen sometimes uses these)

# Allow inline HTML (Doxygen commands, <br>, etc.)
MD033: false

# Allow bare URLs (often useful in docs)
MD034: false

# Headings spacing (safe defaults)
MD022: true
MD023: true

# Lists indentation – be permissive
MD007:
  indent: 2
